name: Build AI App

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Tools
        run: pip install flet openai

      - name: Build APK File
        run: yes "y" | flet build apk

      - name: Upload Mobile App
        uses: actions/upload-artifact@v4
        with:
          name: Super_AI_Agent_V1
          path: build/apk/**/*.apk
          
